"""
book_deep.py — book-level depth for the newspaper's Book section.

BOOK_LESSONS in newspaper.py rotates a *chapter* lesson daily. This module adds
the layer underneath it, keyed by book title:

    crux      — the whole book in 10+ points. Read this and you have the book.
    learnings — what actually changes in your head after reading it.
    examples  — concrete cases from the book or from applying it.
    adapt     — how it lands in this life specifically: FP&A, Dubai, the SIP,
                the trading desk, a daughter who is 8 months old.

Keyed by book rather than by chapter on purpose: 48 chapter entries map to 29
books, and a "full book crux" is a property of the book, not the chapter. Any
book missing from here degrades gracefully — the section just renders the
chapter lesson as before.
"""
from __future__ import annotations

BOOK_DEEP: dict[str, dict] = {

    # ── Habits, focus, systems ────────────────────────────────────────────────
    "Atomic Habits": {
        "crux": [
            "You do not rise to the level of your goals. You fall to the level of your systems.",
            "1% better daily compounds to 37x in a year. 1% worse decays to 0.03x.",
            "Habits form on a four-step loop: cue → craving → response → reward.",
            "Build good habits: make it obvious, attractive, easy, satisfying. Invert all four to break one.",
            "Identity drives behaviour, not the reverse. 'I don't smoke' beats 'I'm trying to quit'.",
            "Every action is a vote for the person you are becoming. Majority wins, not unanimity.",
            "The two-minute rule: a new habit must take under two minutes to start.",
            "Environment beats willpower. Motivation is overrated; friction is decisive.",
            "Habit stacking: after [existing habit], I will [new habit]. The old habit becomes the cue.",
            "You need a plateau of latent potential. Results lag effort — most people quit inside the lag.",
            "Never miss twice. One miss is an accident. Two is the start of a new habit.",
            "Measure what you want to repeat. An unrecorded habit drifts within three weeks.",
        ],
        "learnings": [
            "Discipline is a design problem, not a character problem.",
            "The gap between effort and visible result is where nearly everyone quits.",
            "Systems survive bad days. Motivation does not.",
            "Tracking is not admin. Tracking is the habit.",
        ],
        "examples": [
            "British Cycling went from one Tour de France win in 110 years to five in six years by stacking 1% gains — pillow hygiene, hand-washing, bike paint for dust visibility.",
            "Clear's own recovery: a bat to the face at 15, two years of rebuilding, then an academic All-American — built entirely on sleep and study routines, not talent.",
            "Twice-weekly gym attendance beats a 90-minute session once a month, even though the monthly total is similar. Frequency builds identity; volume does not.",
        ],
        "adapt": [
            "Score one caption per day before posting. The score is the habit, not the post.",
            "Two-minute rule on the Dubai job hunt: open the tracker and add one company. That is the whole commitment.",
            "SIP on auto-debit the day salary lands. Remove the monthly decision entirely.",
            "Never miss twice on the daily brief. One skipped morning is fine. Two means the system broke.",
        ],
    },

    "Deep Work": {
        "crux": [
            "Deep work: focused, undistracted, cognitively demanding work. It is becoming rare and simultaneously more valuable.",
            "Two core abilities now decide income: learn hard things fast, and produce elite output fast.",
            "Both abilities depend on deep work. Both are destroyed by fragmented attention.",
            "Shallow work is logistically necessary and infinitely replaceable. It feels like work and produces nothing durable.",
            "Attention residue: switching tasks leaves cognitive drag for 15–20 minutes. Ten switches cost you the day.",
            "High-quality work = time spent × intensity of focus. Intensity is the neglected multiplier.",
            "Four scheduling philosophies: monastic, bimodal, rhythmic, journalistic. Rhythmic — same hours daily — is the only one most people can sustain.",
            "Willpower is finite and depletes. Rituals and fixed locations spend none of it.",
            "Schedule every minute of the workday. Not to obey it, but to force the question 'what deserves this hour?'",
            "Fixed-schedule productivity: hard-stop the day and work backwards. Constraint forces ruthless triage.",
            "Boredom tolerance is trainable and prerequisite. If every queue is filled with a phone, focus never develops.",
            "Quit social media by default; readmit a tool only if it clearly serves a core goal.",
            "Drain the shallows. Aim shallow work under 40% of the week and defend the rest.",
        ],
        "learnings": [
            "Busy is not a proxy for valuable. It is usually a proxy for unfocused.",
            "The ability to concentrate is a skill you build, not a mood you catch.",
            "Fragmented time is not additive — four 30-minute blocks are worth far less than one 2-hour block.",
            "Downtime is not idleness; unconscious processing needs it.",
        ],
        "examples": [
            "Carl Jung built a stone tower at Bollingen and wrote there in the mornings, uninterrupted, while running a clinical practice.",
            "Adam Grant compressed teaching into one semester and batched research into the other — becoming one of the most published psychologists of his generation.",
            "Newport wrote a book, earned a PhD, and published peer-reviewed papers while rarely working past 5:30pm, by hard-stopping his day.",
        ],
        "adapt": [
            "One 90-minute block before 8am for the highest-leverage build. Phone in another room, not face-down on the desk.",
            "Batch Telegram, Instagram, and email into two windows. Notifications off outside them.",
            "Financial models are deep work. Do them before the market opens, never in gaps between messages.",
            "Hard-stop at 7pm on weekdays. The constraint is what forces the triage.",
        ],
    },

    "Essentialism": {
        "crux": [
            "Almost everything is noise. Very few things are exceptionally valuable.",
            "The undisciplined pursuit of more is how capable people stall.",
            "Replace 'How can I do it all?' with 'What is the one thing I should do?'",
            "If you don't prioritise your life, someone else will.",
            "Trade-offs are unavoidable. Pretending otherwise means choosing badly by default.",
            "Explore widely before committing narrowly. More options examined, fewer selected.",
            "Apply extreme criteria: not 'is this good?' but 'is this the best possible use of this time?'",
            "'No' is a complete sentence. The discomfort of refusing lasts minutes; the cost of agreeing lasts months.",
            "Sunk cost is not a reason. Ask what you would pay to acquire this commitment today.",
            "Buffer time by 50%. Every plan without slack fails on contact with reality.",
            "Remove the bottleneck rather than working harder around it.",
            "Small wins beat big launches. Progress is the most effective motivator known.",
            "Essentialism is a discipline, not a one-time purge. The noise regrows weekly.",
        ],
        "learnings": [
            "Saying yes to everything is a decision — usually a bad one made passively.",
            "The cost of a commitment is every alternative you can no longer take.",
            "Capable people get buried precisely because they are capable.",
            "Slack is not waste. Slack is what absorbs reality.",
        ],
        "examples": [
            "Southwest Airlines said no to meals, assigned seating, and hub routing — and stayed profitable for decades while full-service rivals collapsed.",
            "Warren Buffett attributes most of his wealth to roughly ten decisions, having passed on thousands.",
            "McKeown attended a client meeting hours after his daughter's birth. He got neither the client's respect nor the moment back — the book's founding regret.",
        ],
        "adapt": [
            "Five active projects maximum. TradeFlow, Codex, Meta recovery, Dubai, SIP. A sixth means one gets cut, not squeezed in.",
            "Before any new build: what does this replace? If nothing, it doesn't start.",
            "Kill features that no measurement supports. The deleted /fno and /options pages were the right call.",
            "Buffer every deadline by 50%. A model promised Friday gets built by Wednesday.",
        ],
    },

    "The ONE Thing": {
        "crux": [
            "The focusing question: what's the ONE thing I can do, such that by doing it everything else gets easier or unnecessary?",
            "Success is sequential, not simultaneous. One domino at a time.",
            "A 2-inch domino can topple one 50% larger. Twenty-three dominoes in sequence reach the moon.",
            "Multitasking is a lie. The brain task-switches, and each switch costs time and accuracy.",
            "Willpower is a battery, not a trait. Spend it on the ONE thing, early.",
            "A balanced life is a myth. Counterbalance instead: go extreme on priorities, then return.",
            "Big is not bad. Thinking small caps the outcome before you start.",
            "Time-block the ONE thing first — four hours, daily, protected before anything else enters the calendar.",
            "Protect the block like a surgeon protects theatre time. Interruption is not negotiable.",
            "Goal-set to the now: someday → 5-year → 1-year → month → week → today.",
            "Productivity is not doing more things. It is doing the right thing until it compounds.",
            "Four thieves: inability to say no, fear of chaos, poor health habits, an environment that doesn't support the goal.",
        ],
        "learnings": [
            "Priorities plural is a contradiction. The word had no plural for 500 years.",
            "Extraordinary results come from narrow, sustained focus — not from breadth.",
            "If everything is important, nothing gets finished.",
            "Chaos elsewhere is the price of excellence somewhere. Accept it consciously.",
        ],
        "examples": [
            "Gary Keller rebuilt Keller Williams by replacing 14 executives and focusing on one thing at a time; it became the largest real-estate firm in the US.",
            "Pat Matthews sold one painting after a year, then committed to one painting per day. Within two years he was selling at $10,000 each.",
            "The Colonel spent years on one recipe and one method before franchising anything.",
        ],
        "adapt": [
            "Weekly: name the ONE thing that makes the Dubai offer likelier. Usually it is one specific application done properly, not ten sent.",
            "Time-block 6–8am for it. Everything else takes what remains.",
            "On TradeFlow: ship the measured equity engine well before adding a fifth page.",
            "Counterbalance, don't balance. Job-hunt sprints will cost evenings. Say so out loud and repay the time after.",
        ],
    },

    "The Checklist Manifesto": {
        "crux": [
            "Failure in complex work is usually not ignorance. It is ineptitude — knowing what to do and not doing it.",
            "Volume and complexity of knowledge now exceed what any individual can reliably hold in working memory.",
            "Checklists convert known steps into guaranteed steps.",
            "Two failure types: errors of ignorance (we don't know) and errors of ineptitude (we know but slipped). Checklists kill the second.",
            "Good checklists are short — 5 to 9 items, one page, pause points at natural breaks.",
            "Bad checklists are long, vague, and try to spell out every step. They get ignored.",
            "DO-CONFIRM (act, then verify) versus READ-DO (read each line, then act). Pick deliberately.",
            "Checklists must be tested in the real setting. Desk-designed lists fail in the field.",
            "The largest gain is often communication: forcing names, roles, and concerns to be stated aloud.",
            "A five-item surgical checklist cut deaths 47% and complications 36% across eight hospitals.",
            "Experts resist checklists because they feel insulting. That reaction is the reason they are needed.",
            "Discipline is harder than brilliance, and rarer.",
        ],
        "learnings": [
            "Skill does not protect against the routine slip. Structure does.",
            "The resistance to a checklist is ego, and ego is expensive.",
            "Writing the list down is what converts intention into reliability.",
            "Forcing people to speak up is a safety feature, not politeness.",
        ],
        "examples": [
            "Boeing's Model 299 crashed in 1935 because pilots forgot one lock. A one-page checklist let the B-17 fly 1.8 million miles without a similar accident.",
            "Johns Hopkins used a five-line central-line checklist and cut infection rates from 11% to zero over a year.",
            "Van Halen's brown-M&M clause was a checklist canary: if the M&Ms were unsorted, the rigging had not been read either.",
        ],
        "adapt": [
            "Pre-post checklist for Instagram: score the caption, check restricted terms, confirm no financial-advice phrasing. Five items, one screen.",
            "Pre-deploy checklist: type-check, lint, verify which Vercel project the alias actually points at.",
            "Month-end close checklist. Same order every month. Speed comes from the order, not from hurrying.",
            "Pre-trade checklist: regime, stop distance versus ATR, position already open? The 59 duplicate NATGAS rows were an ineptitude error, not an ignorance one.",
        ],
    },

    # ── Money, risk, probability ─────────────────────────────────────────────
    "The Psychology of Money": {
        "crux": [
            "Doing well with money has little to do with intelligence and everything to do with behaviour.",
            "No one is crazy. Every money decision makes sense given that person's specific history of experience.",
            "Luck and risk are the shadow siblings of every outcome. Neither is measurable, both are decisive.",
            "There is no reason to risk what you have for what you don't need.",
            "Compounding is counterintuitive: $81.5bn of Buffett's $84.5bn arrived after his 65th birthday.",
            "Getting money and keeping money are different skills. The second requires frugality and paranoia.",
            "Tails drive everything. A minority of events account for the majority of outcomes.",
            "The highest dividend money pays is control over your own time.",
            "Wealth is what you don't see. Spending is evidence of spending, not of wealth.",
            "Save without a specific goal. Savings buy optionality against a world you cannot forecast.",
            "Room for error is the single most underrated force. Plan for the plan not going to plan.",
            "Avoid extreme financial commitments — your future self's goals will not match your current ones.",
            "Volatility is the fee for high returns, not a fine for a mistake. Fees you pay willingly; fines you avoid.",
            "Define the game you are playing, and stop taking cues from people playing a different one.",
        ],
        "learnings": [
            "A mediocre strategy held for 30 years beats a brilliant one abandoned in year 3.",
            "Most financial mistakes are emotional, so most financial fixes must be behavioural.",
            "Survival is the prerequisite for compounding. Everything else is secondary.",
            "Your risk tolerance is not a number. It is what you actually do at a 40% drawdown.",
        ],
        "examples": [
            "Ronald Read, a petrol-station attendant, left $8m by buying blue chips for decades. Richard Fuscone, Harvard MBA and Merrill executive, went bankrupt in 2008.",
            "Bill Gates went to one of the only high schools on earth with a computer in 1968 — one in a million odds. His equally able friend Kent Evans died climbing.",
            "Buffett's returns are good but not historically unique; his 80-year runway is. Start at 30 instead of 10 and the fortune largely disappears.",
        ],
        "adapt": [
            "SIP ₹5–15K/month for the BMW fund. The consistency matters more than the monthly amount.",
            "Keep 6 months of KL expenses liquid before scaling any trading capital. Room for error first.",
            "Trading capital is separate from family capital. Never one pool.",
            "The Dubai target is AED 30K/month, not 'as much as possible'. Define enough or the goalpost moves forever.",
        ],
    },

    "Thinking in Bets": {
        "crux": [
            "Every decision is a bet on an uncertain future. Certainty is not available.",
            "Outcome ≠ decision quality. Chess is nearly all skill; life is poker — skill plus luck.",
            "'Resulting' is judging a decision by how it turned out. It is the core error.",
            "Replace true/false with a confidence percentage. 'I'm 70% on this' is honest and updatable.",
            "Saying 'I'm not sure' is a strength. Pretended certainty blocks learning.",
            "Beliefs are formed first and vetted later, if ever. Assume yours are unaudited.",
            "Motivated reasoning: contradicting evidence gets scrutinised, confirming evidence gets waved through.",
            "Self-serving bias: wins are skill, losses are luck. This makes experience useless.",
            "Build a truth-seeking group with an explicit charter: accuracy over comfort, dissent welcomed.",
            "Argue the other side properly. Steelman it, don't strawman it.",
            "Separate signal from noise in feedback. A small sample tells you almost nothing.",
            "Use temporal distance — 10 minutes, 10 months, 10 years — before deciding under emotion.",
            "Backcast from success and pre-mortem from failure. Both, not one.",
            "Tilt is real. Recognise the emotional state and stop deciding while in it.",
        ],
        "learnings": [
            "A good decision can lose. A bad decision can win. Track process, not scoreboard.",
            "Confidence expressed as a percentage is falsifiable. Confidence expressed as certainty is not.",
            "Without separating luck from skill, ten years of experience teaches nothing.",
            "You need people who will tell you that you were wrong.",
        ],
        "examples": [
            "Pete Carroll's Super Bowl XLIX pass call was widely branded the worst in history. The interception rate on that play was about 2% — the decision was defensible, the outcome was not.",
            "Duke won $4m at poker by focusing on decision quality across thousands of hands rather than the result of any single one.",
            "In 1979, near-universal belief that Nixon's tapes would exonerate him did not survive contact with the tapes. Consensus is not evidence.",
        ],
        "adapt": [
            "Log every trade with the thesis and a confidence %, not just entry and exit. The ledger is the point.",
            "45.8% win rate at +0.171R is a good system. Judge it on 459 trades, not on last week.",
            "After a losing trade, ask what a repeat of that decision returns over 100 tries. Usually the answer is 'fine'.",
            "The 50% real win rate on the signals feed is the honest number. Publish that, not the flattering one.",
        ],
    },

    "Thinking, Fast and Slow": {
        "crux": [
            "Two systems: System 1 is fast, automatic, emotional. System 2 is slow, effortful, logical.",
            "System 2 is lazy and endorses System 1's answers with minimal checking.",
            "What you see is all there is (WYSIATI). The mind builds confident stories from whatever is available.",
            "Anchoring: an irrelevant number moves your estimate. Knowing this does not stop it.",
            "Availability: vivid and recent events feel probable. Frequency gets confused with memorability.",
            "Representativeness beats base rates. People pick the plausible story over the likelier category.",
            "Loss aversion: losses hurt roughly 2x as much as equivalent gains please.",
            "Prospect theory: you evaluate from a reference point, not in absolutes. Framing changes the answer.",
            "Overconfidence is the most consequential bias, and expertise increases it.",
            "The illusion of validity: confidence tracks story coherence, not predictive accuracy.",
            "Regression to the mean explains most 'turnarounds' and most 'losses of form'.",
            "The planning fallacy: forecasts default to best-case. Use the outside view and comparable past cases.",
            "The remembering self and the experiencing self disagree. Memory is dominated by peaks and endings.",
            "Formulas beat expert intuition in noisy, low-validity environments. Checklists and algorithms win.",
        ],
        "learnings": [
            "You cannot debias yourself by intention. You can build procedures that catch the bias.",
            "Fluency masquerades as truth. Anything easy to process feels more likely.",
            "Expert intuition is real only where feedback is fast and regular. Markets do not qualify.",
            "Write the forecast down before the outcome, or hindsight will rewrite it.",
        ],
        "examples": [
            "Israeli parole judges granted parole ~65% of the time right after a meal break and near 0% just before one. Same evidence, different glucose.",
            "The Linda problem: most people rate 'bank teller and feminist' as likelier than 'bank teller', which is logically impossible.",
            "Kahneman's flight-instructor insight: praise after a good flight seemed to hurt and criticism after a bad one seemed to help. It was regression to the mean, not feedback working.",
        ],
        "adapt": [
            "Write the trade thesis before entry. Post-hoc explanation is System 1 inventing a story.",
            "Use base rates on the Dubai search: what fraction of applications convert? Plan on that, not on the best case.",
            "The planning fallacy is why estimates slip. Take the outside view — how long did the last comparable build actually take?",
            "Backtest numbers over gut feel. -0.029R on 1H means the 1H feeling is wrong, however strong it is.",
        ],
    },

    "Poor Charlie's Almanack": {
        "crux": [
            "Build a latticework of mental models from many disciplines. One-model thinking distorts every problem.",
            "To the man with a hammer, every problem looks like a nail. Most professionals are that man.",
            "Invert, always invert. Ask how to fail, then avoid that.",
            "Know your circle of competence and stay inside it. The edge is knowing where the edge ends.",
            "Incentives explain most behaviour. Look at the incentive before assuming intent.",
            "The psychology of misjudgement runs about 25 standard biases. Learn them as a checklist.",
            "Opportunity cost is the correct filter for every decision.",
            "Sit on your hands. Great opportunities are rare; act rarely and heavily.",
            "Avoid the three big destroyers: alcohol, leverage, and envy. Envy is the stupidest.",
            "Multiply models: compound interest, scale, backup systems, breakpoints, critical mass.",
            "A great business at a fair price beats a fair business at a great price.",
            "Read constantly. Neither Munger nor Buffett knows a wise person who doesn't read all the time.",
            "Be reliable. Unreliability cancels every virtue you have.",
            "Take a simple idea and take it seriously. That is the whole method.",
        ],
        "learnings": [
            "Avoiding stupidity beats seeking brilliance, and it is far more achievable.",
            "Inversion surfaces risks that forward thinking never reaches.",
            "Most bad decisions come from one model applied where it doesn't fit.",
            "Patience is a strategy, not a personality trait.",
        ],
        "examples": [
            "Munger's Costco analysis combines scale economics, incentive design, and psychology at once — no single-discipline read explains it.",
            "See's Candies: Berkshire paid up for brand pricing power in 1972 and it returned over $2bn on a $25m outlay.",
            "Munger rebuilt from a divorce, no money, and the death of his 9-year-old son to become a billionaire. Reliability compounded.",
        ],
        "adapt": [
            "Invert the Dubai plan: what guarantees no offer by mid-2026? Then remove those causes.",
            "Circle of competence: Indian equities and FP&A. Polymarket stays paper-only until 200 trades say otherwise.",
            "Check incentives before trusting any financial content, including your own.",
            "Sit on your hands when the regime filter says no. Not trading is a position.",
        ],
    },

    "Antifragile": {
        "crux": [
            "Three categories: fragile (breaks under stress), robust (resists), antifragile (improves).",
            "The opposite of fragile is not robust. It is antifragile — gaining from disorder.",
            "Absence of evidence of fragility is not evidence of robustness. Turkeys learn this at Thanksgiving.",
            "Via negativa: improvement comes more reliably from removal than addition.",
            "Barbell strategy: extreme safety on most of the exposure, extreme risk on a small slice. Never the middle.",
            "Optionality lets you gain from uncertainty without needing to forecast it.",
            "Hormesis: small doses of stress strengthen. Zero stress atrophies.",
            "Naive intervention causes iatrogenic harm — the cure does the damage. Doing nothing is often correct.",
            "Skin in the game is the only real filter. Ignore forecasts from people who bear no cost for being wrong.",
            "Fragility is measurable and predictable; future events are not. Measure the exposure, not the odds.",
            "Time is the best test of durability. The Lindy effect: what has survived long tends to keep surviving.",
            "Redundancy looks inefficient and is actually insurance. Nature runs two kidneys.",
            "Small and decentralised is antifragile; large and centralised is fragile.",
            "Touristification — removing all volatility — makes systems and people brittle.",
        ],
        "learnings": [
            "Optimise for surviving the worst case, not for the expected case.",
            "Removing the bad reliably beats adding the good.",
            "Anyone forecasting without downside exposure should be discounted to zero.",
            "Efficiency and fragility are usually the same thing wearing different clothes.",
        ],
        "examples": [
            "Restaurants are individually fragile and the restaurant sector is antifragile — constant failure improves the survivors.",
            "The 2008 banking system was optimised for efficiency, held minimal buffers, and broke. Small distributed lenders did not.",
            "Taleb's barbell in practice: 90% in treasuries, 10% in far out-of-the-money options. Capped loss, uncapped gain.",
        ],
        "adapt": [
            "Barbell the income: stable FP&A salary as the safe leg, Codex and trading as the small convex leg. No middle-risk bets.",
            "Multiple income paths beat one optimised one. Meta restriction proved single-channel dependence is fragile.",
            "Via negativa on the product: deleting /fno, /options, /portfolio improved TradeFlow. Removal was the upgrade.",
            "Redundancy on the bots: Railway shut down and took the command handler with it. One host is one point of failure.",
        ],
    },

    # ── Startups, strategy, competition ──────────────────────────────────────
    "Zero to One": {
        "crux": [
            "Progress is either 0→1 (new things) or 1→n (copying). Copying does not create new value.",
            "The contrarian question: what important truth do very few people agree with you on?",
            "Competition is for losers. Perfect competition drives profit to zero by definition.",
            "Monopoly is the condition of every genuinely valuable business. All happy companies are different.",
            "Four monopoly traits: proprietary technology, network effects, economies of scale, branding.",
            "Proprietary tech must be 10x better than the alternative, not marginally better.",
            "Start with a small market you can dominate, then expand. Big markets are a red flag.",
            "Last-mover advantage beats first-mover. What matters is the last big cash flow.",
            "Power law: one investment returns more than all others combined. This applies to careers too.",
            "Definite optimism builds the future. Indefinite optimism just expects it to arrive.",
            "Sales matters as much as product, and engineers systematically underrate it.",
            "Seven questions every business must answer: engineering, timing, monopoly, people, distribution, durability, secret.",
            "Secrets still exist. The belief that everything is known is why so little gets found.",
            "Founders should ask: will this still be valuable in 10 years?",
        ],
        "learnings": [
            "If you're competing on the same axis as everyone else, the margin is already gone.",
            "Small dominated market first. Broad ambition second.",
            "Power laws mean concentration beats diversification for effort allocation.",
            "Distribution is not an afterthought. A product nobody hears about does not exist.",
        ],
        "examples": [
            "PayPal targeted eBay power sellers — 20,000 people — rather than 'online payments'. Domination first, expansion after.",
            "Google has held roughly two-thirds of search since 2002 and prints margins that a competitive market would have erased.",
            "Facebook started at one university with 100% of that market, then expanded campus by campus.",
        ],
        "adapt": [
            "Codex's edge is not 'AI automation'. It is a specific workflow for a specific buyer at $47. Dominate that.",
            "The faceless FP&A page competes in a narrower niche than generic finance content. That narrowness is the asset.",
            "10x, not 10%: a signals product must be clearly better than a free Telegram channel, not slightly.",
            "Distribution for the Dubai search is the network, not the CV. Applications without referrals are 1→n.",
        ],
    },

    "The Lean Startup": {
        "crux": [
            "A startup is an organisation built to find a repeatable business model under extreme uncertainty.",
            "Build–Measure–Learn. Speed through the loop is the core competency.",
            "Validated learning is the unit of progress, not code shipped or hours worked.",
            "Minimum Viable Product: the smallest thing that tests the riskiest assumption.",
            "Two leap-of-faith assumptions: value (do they want it?) and growth (how does it spread?).",
            "Genchi genbutsu — go and see. Talk to actual users, not to your model of them.",
            "Vanity metrics (totals, page views) flatter. Actionable metrics (cohort retention, conversion) inform.",
            "Cohort analysis and split testing are the only honest reads on whether you improved anything.",
            "Innovation accounting: define the baseline, tune the engine, then pivot or persevere.",
            "Three growth engines: sticky (retention), viral (referral), paid (unit economics). Pick one.",
            "Pivot types: zoom-in, zoom-out, customer segment, platform, business architecture, value capture.",
            "Small batches expose problems immediately. Large batches hide them until launch.",
            "Stop the line — fix root causes with five whys rather than shipping over them.",
            "The question is never 'can we build this?' It is 'should we build this?'",
        ],
        "learnings": [
            "Shipping is not progress. Learning is progress.",
            "Most feature work is waste because most assumptions are wrong.",
            "A metric that only goes up is not telling you anything.",
            "Deciding to pivot late is the expensive part, not the pivot itself.",
        ],
        "examples": [
            "Dropbox tested demand with a 3-minute video before building sync. Beta waitlist went 5,000 → 75,000 overnight.",
            "Zappos began by photographing shoes in local shops and buying at retail per order — testing willingness to buy online before holding inventory.",
            "Ries's IMVU spent months on an IM-interoperability feature nobody used. Users didn't want to add friends; they wanted new ones.",
        ],
        "adapt": [
            "Codex at $47: test the tier with a landing page and real payment intent before building the full product.",
            "The signal edge measurement was validated learning — t=+2.87 on daily equity, noise on 1H. That result should drive the roadmap.",
            "Cohort the newspaper: are the same readers returning, or is it new traffic each morning? Totals won't tell you.",
            "Five whys on the alert flood: no time stop → because no lifecycle rule → because the backtest's horizon was never ported to live code.",
        ],
    },

    "The Innovator's Dilemma": {
        "crux": [
            "Well-managed companies fail precisely by doing what good management prescribes.",
            "Sustaining innovations improve products for existing customers. Incumbents win these reliably.",
            "Disruptive innovations start worse on the metrics incumbents value, and win anyway.",
            "Disruption enters at the low end or in a new market, where incumbent margins look unattractive.",
            "Listening closely to your best customers pushes you away from disruptive bets. Rationally.",
            "Resource dependence: customers and investors, not managers, effectively allocate the resources.",
            "Small markets cannot solve the growth needs of large companies, so large companies skip them.",
            "Technology supply often outruns demand — products overshoot what users need, opening the low end.",
            "The basis of competition shifts over time: function → reliability → convenience → price.",
            "You cannot analyse markets that do not yet exist. Discovery-driven planning, not forecasting.",
            "Disruption must be housed in an independent organisation small enough to be excited by a small win.",
            "Failure early and cheaply is the plan, because the first strategy will be wrong.",
        ],
        "learnings": [
            "Doing everything right is not protection when the game changes underneath.",
            "The customers who fund you today are the reason you miss tomorrow.",
            "A market too small to matter now is the only place disruption can start.",
            "Cost structure determines which opportunities look attractive. It is destiny.",
        ],
        "examples": [
            "Disk drives: every generational shift from 14-inch to 1.8-inch killed the leader, though each new size was initially worse on capacity.",
            "Kodak invented the digital camera in 1975 and could not commit to it without cannibalising film margins.",
            "Mini-mills started with low-grade rebar that integrated steel mills were happy to abandon, then moved up until they took the whole market.",
        ],
        "adapt": [
            "A free Telegram bot is the low-end disruption of paid research. That is the position to hold, not apologise for.",
            "Codex at $47 looks unattractive next to consulting rates. That is exactly why it has room.",
            "Don't let existing dashboard users dictate the roadmap if the measured edge points elsewhere.",
            "Keep experiments in separate ledgers — the APEX poly engine on its own books, so a small bet stays a small bet.",
        ],
    },

    "The E-Myth Revisited": {
        "crux": [
            "The fatal assumption: understanding the technical work means understanding a business that does that work.",
            "Every owner is three people — Technician (does), Manager (orders), Entrepreneur (envisions) — usually 70/20/10.",
            "Working in your business is not working on your business.",
            "Business life cycle: Infancy (you do everything), Adolescence (past capacity), Maturity (systems run it).",
            "Most businesses collapse in adolescence, when the owner's capacity is the ceiling.",
            "Build the business as the prototype for 5,000 more, even if you only ever want one.",
            "The Franchise Prototype: systems-dependent, not people-dependent.",
            "Work on the business as if you intend to sell it. That forces documentation.",
            "Hire ordinary people and give them extraordinary systems, rather than hunting for extraordinary people.",
            "Your Primary Aim comes before the business plan. What is the life this business is for?",
            "Seven development programmes, starting with the innovation–quantification–orchestration cycle.",
            "Quantify everything. Without numbers you cannot see the business at all.",
            "Documentation is what turns a job into an asset.",
        ],
        "learnings": [
            "Being excellent at the craft is what traps most skilled people in a job they own.",
            "If it only works when you do it, you built a job, not a business.",
            "Systems are the product. The output is a by-product.",
            "Quantify before you optimise, or you are guessing.",
        ],
        "examples": [
            "Sarah's pie shop: superb baker, failing business. She loved baking and hated owning, and never noticed the difference.",
            "McDonald's succeeded on operational systems, not recipes — every store reproducible by teenagers.",
            "The hotel Gerber describes ran on documented detail: turndown at a set time, a specific glass, a specific note. The system produced the feeling.",
        ],
        "adapt": [
            "Document the newspaper pipeline so it survives you not touching it. GitHub Actions is already most of the way there.",
            "Codex must run without your hands in it — that is the difference between a product and freelancing.",
            "Quantify the content engine: posts per week, score distribution, follower delta. No numbers, no view.",
            "Every manual step in the trading stack is a step that fails when you are busy interviewing in Dubai.",
        ],
    },

    # ── Leadership, management, organisations ────────────────────────────────
    "Good to Great": {
        "crux": [
            "Good is the enemy of great. Most organisations never become great because they become good enough.",
            "Level 5 Leadership: extreme personal humility combined with intense professional will.",
            "First Who, Then What. Get the right people on the bus before setting direction.",
            "Confront the brutal facts while never losing faith — the Stockdale Paradox.",
            "The Hedgehog Concept: the intersection of what you're deeply passionate about, what you can be best in the world at, and what drives your economics.",
            "One economic denominator — profit per X — clarifies the entire business.",
            "A culture of discipline, not a tyrant imposing discipline.",
            "Technology accelerates momentum; it never creates it.",
            "The Flywheel: relentless pushing in a consistent direction until momentum compounds.",
            "The Doom Loop is the opposite — new programmes, new directions, no accumulation.",
            "Great companies had no miracle moment. Transformation looked dramatic only from outside.",
            "Stop-doing lists matter more than to-do lists.",
            "Compensation gets the right people on the bus; it does not motivate the wrong ones.",
        ],
        "learnings": [
            "Who beats what. Wrong people make the right strategy fail.",
            "Facing bad news early is a competitive advantage.",
            "Momentum accumulates from consistent direction, not from bursts of intensity.",
            "Greatness is mostly a series of unglamorous, consistent decisions.",
        ],
        "examples": [
            "Walgreens beat the market 15x from 1975–2000 by fixating on profit per customer visit — one metric, relentlessly.",
            "Darwin Smith at Kimberly-Clark sold the paper mills — the company's historic core — to enter consumer paper against P&G. Shareholder returns beat the market 4x.",
            "Nucor's flywheel: mini-mill technology → lower cost → market share → more mills. Same push for decades.",
        ],
        "adapt": [
            "Hedgehog: CA precision + FP&A + building with AI. That intersection is narrower and stronger than 'finance content'.",
            "Economic denominator for Codex: profit per customer, not downloads.",
            "Brutal fact: 1H signals have no measurable edge. Faith: the daily equity engine does. Hold both.",
            "Stop-doing list beats the roadmap. Deleting three TradeFlow pages was the flywheel push.",
        ],
    },

    "Built to Last": {
        "crux": [
            "Visionary companies are built to outlast any single leader, product, or idea.",
            "Be a clock builder, not a time teller. Build the organisation, not the one great idea.",
            "The genius of AND rejects the tyranny of OR — purpose AND profit, stability AND change.",
            "Preserve the core, stimulate progress. The core ideology is fixed; everything else is negotiable.",
            "Core ideology = core values + purpose. It is discovered, not written by committee.",
            "BHAGs — big hairy audacious goals — with a 10 to 30-year horizon.",
            "Cult-like cultures: intense indoctrination, tight fit, elitism. You either belong or you leave.",
            "Try a lot of stuff and keep what works. Evolutionary progress, not just planned strategy.",
            "Home-grown management preserves the core across generations. Outside saviours break it.",
            "Good enough never is. Continuous self-improvement is institutionalised, not motivational.",
            "Great companies are not started by charismatic visionaries with a great idea — often the opposite.",
            "Alignment is the work: every practice must reinforce the ideology or it erodes it.",
        ],
        "learnings": [
            "Build the machine that produces outcomes, not the outcome.",
            "Refusing the trade-off is often the more interesting option.",
            "Values only count when they cost you something.",
            "Continuity of the core is what allows aggressive change everywhere else.",
        ],
        "examples": [
            "3M's 15% time and 'sell no new products' discipline produced Post-it Notes through evolutionary trial, not strategy.",
            "HP kept its core people-first ideology across decades of complete product reinvention, from oscillators to printers.",
            "Boeing bet the company on the 707 and again on the 747 — BHAGs that could have ended it.",
        ],
        "adapt": [
            "Core ideology for the brand: numbers first, no filler, no fake certainty. That does not change with platform.",
            "BHAG: AED 30K/month by mid-2026 and a self-running product stack. Both dated, both audacious.",
            "Preserve the core, change the channel — the Meta restriction changes distribution, not the voice.",
            "Build the newspaper so it publishes without you. Clock, not time.",
        ],
    },

    "High Output Management": {
        "crux": [
            "A manager's output is the output of their organisation plus the organisations they influence.",
            "Managerial leverage = output ÷ time spent. Optimise for leverage, not effort.",
            "Highest-leverage activities: training, and setting direction that many people then act on.",
            "Production has three constraints everywhere: quality, cost, delivery time.",
            "Inspect at the earliest, cheapest stage. Fixing at the end costs orders of magnitude more.",
            "Indicators must come in pairs — one for output, one for the quality you might sacrifice for it.",
            "Meetings are the medium of managerial work. A bad meeting is a process failure, not a waste of time in general.",
            "One-on-ones are the highest-leverage meeting. The subordinate sets the agenda.",
            "Decisions should be made at the lowest level with both knowledge and responsibility.",
            "Aim for peer decision-making, then clear commitment even from dissenters.",
            "Task-relevant maturity determines management style: low TRM needs structure, high TRM needs delegation.",
            "Delegation without follow-through is abdication.",
            "Performance reviews exist to improve performance, not to rank people.",
            "Three motivators when money is sufficient: competence, achievement, and self-actualisation.",
        ],
        "learnings": [
            "Leverage is the only useful lens on how a manager spends an hour.",
            "Paired indicators stop you optimising one number into a disaster.",
            "Training your team is not overhead. It is the highest-return activity available.",
            "Catch problems at the cheapest stage — the value-add curve is brutal.",
        ],
        "examples": [
            "Grove's breakfast-factory model teaches limiting-step scheduling, quality gates, and capacity planning with eggs and toast.",
            "Intel's move out of memory into microprocessors was executed through middle managers reallocating capacity before senior leadership formally decided.",
            "Grove taught a class himself for years — one lecture, hundreds of managers, permanent leverage.",
        ],
        "adapt": [
            "FP&A leverage: build the model once so 20 people read it right, instead of answering 20 questions.",
            "Pair every metric: signals sent AND measured expectancy. One alone produced 180 alerts.",
            "Inspect early — type-check and lint before commit, not after deploy.",
            "In the Dubai role, one-on-ones with the business owners will be the highest-leverage hour of the week.",
        ],
    },

    "The Hard Thing About Hard Things": {
        "crux": [
            "There is no recipe for the hard things. Every playbook assumes conditions you won't have.",
            "The Struggle is the default state of building something hard, not evidence of failure.",
            "Wartime and peacetime CEOs are different jobs requiring different behaviour.",
            "Take care of the people, the products, and the profits — in that order.",
            "Tell it like it is. People can handle bad news; they cannot handle being managed.",
            "Train your people. Neglecting it is the most common and most expensive omission.",
            "Hire for strength, not absence of weakness. Every strong person has visible flaws.",
            "Management debt, like technical debt, accrues interest: two people in one job, no performance process, unclear ownership.",
            "Titles and promotions need a defined process or politics fills the vacuum.",
            "One-on-ones belong to the employee. Silence there means information is not reaching you.",
            "Minimise politics by designing systems, not by asking people to be less political.",
            "The struggle is where greatness comes from. Courage is a habit built by making hard calls.",
            "Focus on the battlefield you're on, not the one you wish you were on.",
        ],
        "learnings": [
            "Nobody's plan survives. The skill is deciding well without enough information.",
            "Transparency scales trust; managed messaging destroys it.",
            "Management debt compounds faster and quieter than technical debt.",
            "Your psychology is the bottleneck more often than the business is.",
        ],
        "examples": [
            "Loudcloud IPO'd in 2001 into a collapsing market because the private markets were shut — a bad option chosen over a fatal one.",
            "Horowitz sold the managed-services business and pivoted to Opsware with $60m left, telling employees the truth about the odds.",
            "Opsware sold to HP for $1.6bn after multiple near-death moments — none of which the plan anticipated.",
        ],
        "adapt": [
            "Meta restriction is a wartime problem. Recovery work first, growth experiments after.",
            "Say the real number publicly — 50% win rate, not the flattering framing. Trust is the asset.",
            "Management debt in the stack: two entry points writing the same signals with different logic caused the duplicate rows.",
            "The Struggle during the Dubai search is the job, not a sign it isn't working.",
        ],
    },

    "Principles": {
        "crux": [
            "Pain + reflection = progress. Pain alone teaches nothing.",
            "Radical truth and radical transparency, applied consistently, beat politeness.",
            "Embrace reality and deal with it. Wishing it were different is the expensive option.",
            "Use the 5-step process: goals → problems → diagnosis → design → execution.",
            "Ego and blind spots are the two barriers. Both feel like conviction from inside.",
            "Be radically open-minded. Fear of looking wrong is more costly than being wrong.",
            "Thoughtful disagreement: stress-test with believable people rather than argue to win.",
            "Believability-weighted decision making — not all opinions carry equal weight.",
            "Distinguish the machine from yourself. Look at your organisation from above as a designer.",
            "Problems are fuel. Do not tolerate them, but do not hide them either.",
            "Diagnose root causes before designing. Most people jump straight to solutions.",
            "People are wired very differently. Match the person to the role's actual requirements.",
            "Write your principles down. Undocumented principles are moods.",
            "Everything is a machine producing outcomes. Fix the machine, not the instance.",
        ],
        "learnings": [
            "Reflection is the step that converts a bad experience into an asset.",
            "Weight opinions by track record, not seniority or volume.",
            "Diagnosis before design is the discipline almost everyone skips.",
            "Writing principles down is what makes them testable.",
        ],
        "examples": [
            "Dalio's 1982 debt-crisis call was catastrophically wrong, cost him the firm, and became the origin of his entire radical-transparency method.",
            "Bridgewater records nearly every meeting so decisions can be audited by anyone. Discomfort is the design goal.",
            "The Dot Collector rates people live in meetings, making believability visible instead of political.",
        ],
        "adapt": [
            "Write the trading principles down. 'Regime filter, structure stop, 48h horizon' beats remembering.",
            "The alert flood is a machine problem, not a bad day. Diagnose the lifecycle rule, don't just clear the backlog.",
            "Believability weighting on market opinions: the backtest outranks anyone's conviction, including yours.",
            "Pain + reflection: the Meta restriction is only useful if the caption scoring process changes because of it.",
        ],
    },

    "Measure What Matters": {
        "crux": [
            "OKRs = Objective (where to go) + Key Results (how you know you got there).",
            "Objectives are qualitative and inspiring. Key results are numeric and time-bound.",
            "If it has no number, it is not a key result.",
            "Focus: 3–5 objectives per cycle. More than that means no priorities.",
            "Align transparently. Everyone's OKRs visible, including the CEO's.",
            "Roughly half of OKRs should be bottom-up, or you get compliance instead of commitment.",
            "Commit publicly. Visibility is what converts a goal into an obligation.",
            "Stretch: aspirational OKRs should land around 70%. Consistent 100% means you set them too low.",
            "Separate committed OKRs (must hit 100%) from aspirational ones (70% is success).",
            "Never tie OKRs to compensation. It corrupts the target-setting immediately.",
            "Track continuously — grade, then continue, update, start over, or stop.",
            "CFRs — Conversations, Feedback, Recognition — replace annual reviews.",
            "OKRs are a vessel, not the content. Bad strategy with good OKRs still fails.",
        ],
        "learnings": [
            "A goal without a number is a wish with better vocabulary.",
            "Transparency is what makes alignment happen without meetings.",
            "70% on a hard target beats 100% on an easy one.",
            "Linking goals to bonuses guarantees sandbagged goals.",
        ],
        "examples": [
            "Intel's Operation Crush retook the microprocessor market from Motorola in 1980, coordinated entirely through OKRs across every function.",
            "Google adopted OKRs at ~40 people and has published them quarterly since. Chrome's 20M→111M user objective drove the browser's whole roadmap.",
            "The Gates Foundation uses OKRs on a $20bn scale to make measurable what was previously a stated intention.",
        ],
        "adapt": [
            "Q3 objective: land the Dubai offer. KRs: 40 targeted applications, 12 first-round calls, 3 finals. Numbers, not effort.",
            "Codex KR: 20 paying customers at $47, not 'launch the product'.",
            "Trading KR: expectancy above +0.15R over 100 live signals. Grade it, then stop or continue.",
            "Grade quarterly and write the number down even when it's 40%. Especially then.",
        ],
    },

    "7 Habits of Highly Effective People": {
        "crux": [
            "Character ethic beats personality ethic. Techniques without character are manipulation.",
            "Paradigms determine what you see. Change the map before optimising the route.",
            "Habit 1 — Be Proactive: between stimulus and response is your freedom to choose.",
            "Focus on your Circle of Influence, not your Circle of Concern. The first grows; the second drains.",
            "Habit 2 — Begin with the End in Mind: write the personal mission statement, then live backwards from it.",
            "Habit 3 — First Things First: Quadrant II (important, not urgent) is where effectiveness lives.",
            "Urgency addiction disguises itself as productivity. Most of Quadrant I is neglected Quadrant II.",
            "Habit 4 — Think Win/Win: scarcity thinking produces win/lose; abundance produces cooperation.",
            "Habit 5 — Seek First to Understand, Then to Be Understood. Diagnose before prescribing.",
            "Empathic listening is the highest-leverage communication skill and almost nobody does it.",
            "Habit 6 — Synergise: 1+1 can equal 3 when differences are valued rather than tolerated.",
            "Habit 7 — Sharpen the Saw: renew physical, mental, social/emotional, spiritual capacity.",
            "P/PC balance: production versus production capability. Killing the goose for the eggs.",
            "The Emotional Bank Account — trust accumulates through deposits and is spent by withdrawals.",
        ],
        "learnings": [
            "Effectiveness is a private victory before it is a public one.",
            "Quadrant II work never announces itself. You must schedule it.",
            "Most communication failures are prescription before diagnosis.",
            "Renewal is not a reward for finishing. It is the capacity to finish.",
        ],
        "examples": [
            "Viktor Frankl in the camps: everything removed except the choice of response. The origin of Habit 1.",
            "Covey's funeral exercise — what four speakers would say about you — reframes goals from achievement to character.",
            "The father who lists his son's faults and cannot understand why the son won't talk. Diagnosis skipped entirely.",
        ],
        "adapt": [
            "Circle of influence on the Meta case: control the caption process, not the platform's decision.",
            "Quadrant II: the Dubai applications and the daughter's bedtime. Neither is urgent. Both decide the decade.",
            "Sharpen the saw is not optional at 7 hours' sleep — it is what makes the analysis correct.",
            "Emotional bank account at home: presence deposits daily. The balance is what carries the hard months.",
        ],
    },

    "Start With Why": {
        "crux": [
            "The Golden Circle: Why → How → What. Most communicate outside-in; leaders work inside-out.",
            "People don't buy what you do. They buy why you do it.",
            "Why is a belief or purpose. How are the differentiating actions. What are the products.",
            "The Golden Circle maps to biology: What is neocortex (rational), Why is limbic (feeling, trust, loyalty).",
            "That is why 'it feels right' outperforms a superior spec sheet.",
            "Manipulations — price, promotions, fear, novelty — produce transactions, not loyalty.",
            "Clarity, discipline, consistency: know why, hold yourself to how, and be consistent in what.",
            "The Law of Diffusion of Innovation: you need 15–18% adoption before the majority moves.",
            "Sell to the people who believe what you believe first. They are the 2.5% who tolerate imperfection.",
            "Why comes from your past, not from a strategy session. It is discovered.",
            "The Celery Test: given your Why, filtering decisions becomes obvious to observers.",
            "Split of Why happens when the What outgrows the belief. Founders' clarity fades and the company drifts.",
            "Why attracts the right people. Skills can be taught; belief cannot.",
        ],
        "learnings": [
            "Purpose is a filter, not a slogan. It should visibly kill options.",
            "Trust is limbic. It does not respond to feature lists.",
            "Early believers are worth more than early volume.",
            "If your Why isn't reflected in what you refuse, you don't have one.",
        ],
        "examples": [
            "Apple sells the same components as Dell but leads with challenging the status quo — and can sell phones and music while Dell could not sell MP3 players.",
            "The Wright brothers beat Samuel Langley, who had funding, Smithsonian backing, and press. They had belief and a team that shared it.",
            "King's 'I have a dream' — not 'I have a plan'. 250,000 arrived without invitations.",
        ],
        "adapt": [
            "Your Why: most financial advice ignores behaviour, so it fails. That belief explains the content, the products, and the refusals.",
            "The Celery Test kills motivational finance content instantly. It doesn't fit the Why.",
            "Sell Codex to the 2.5% who already believe automation beats hiring. Not to the majority.",
            "Lead the Dubai pitch with the belief, not the CV bullet list. The bullets are the What.",
        ],
    },

    # ── Negotiation, people, performance ─────────────────────────────────────
    "Never Split the Difference": {
        "crux": [
            "Negotiation is not rational argument. It is emotional intelligence applied under pressure.",
            "Tactical empathy: recognise and name the other side's perspective without agreeing to it.",
            "Mirroring — repeat their last 1–3 words — keeps them talking and reveals information.",
            "Labelling: 'It seems like…', 'It sounds like…'. Naming a negative defuses it.",
            "Run an accusation audit — list their worst assumptions about you and say them first.",
            "'No' is the start of the negotiation, not the end. It creates safety.",
            "Aim for 'That's right', not 'You're right'. The second means they want you to stop.",
            "Never split the difference. Compromise produces outcomes neither side wanted.",
            "Deadlines are usually artificial and almost always work against whoever fears them.",
            "The F-word: fairness. When they invoke it, they feel wronged. Address that, not the maths.",
            "Bend their reality with anchoring, loss aversion, and non-round numbers.",
            "Calibrated 'How' and 'What' questions transfer the problem without confrontation.",
            "'How am I supposed to do that?' is the most useful sentence in the book.",
            "Find the Black Swan — the unknown that reframes the whole deal. Three types of leverage: positive, negative, normative.",
        ],
        "learnings": [
            "Listening is the tactic, not the courtesy.",
            "Getting to 'no' early saves months of false progress.",
            "Non-round numbers read as calculated; round numbers read as arbitrary.",
            "Compromise is usually mutual loss wearing a diplomatic label.",
        ],
        "examples": [
            "Voss talked down a Brooklyn bank robber using mirroring alone, with no tactical leverage available.",
            "The Chase Manhattan hostage case: 'It seems like you don't want to go back to jail' opened a conversation that demands had closed.",
            "A student negotiated a salary from $30k to $34k plus a defined promotion path by asking 'How am I supposed to accept that?'",
        ],
        "adapt": [
            "Dubai salary talk: anchor with a non-round number — AED 32,400, not 30,000. Then ask how they can get there.",
            "Accusation audit before the offer conversation: 'You're probably thinking I'm asking above the band for this level.'",
            "Label the objection about not having UAE experience before they raise it.",
            "Never split the difference on the SIP amount. Automate the number and remove the negotiation with yourself.",
        ],
    },

    "Mindset": {
        "crux": [
            "Two mindsets: fixed (abilities are static) and growth (abilities develop through effort).",
            "Fixed mindset makes every task a verdict on your worth, so it avoids risk.",
            "Growth mindset treats effort and failure as the mechanism of improvement.",
            "Praising talent produces fragility. Praising process produces resilience.",
            "'Not yet' is the most useful phrase in learning.",
            "Fixed mindset avoids challenges that might reveal limits — and so never finds them.",
            "Effort is what talent requires, not a substitute for it.",
            "Criticism is data in a growth mindset and an attack in a fixed one.",
            "Others' success is inspiration in one frame, threat in the other.",
            "Mindsets are domain-specific. You can be growth-oriented at work and fixed about maths.",
            "Fixed-mindset relationships expect compatibility; growth-mindset relationships expect work.",
            "CEO disease: fixed-mindset leaders need to be the smartest person and suppress bad news.",
            "You can change mindset by noticing the fixed voice and answering it deliberately.",
        ],
        "learnings": [
            "How you explain a failure determines whether you get anything from it.",
            "Talent praise is a trap. Process praise builds durability.",
            "Avoiding challenge to protect self-image caps growth permanently.",
            "'Not yet' converts a verdict into a timeline.",
        ],
        "examples": [
            "Dweck's students given 'you're smart' avoided harder puzzles; those praised for effort chose them and improved.",
            "Michael Jordan was cut from varsity and became famous for practice volume, not gifts.",
            "Lee Iacocca's fixed mindset at Chrysler: early success, then defensiveness, suppressed dissent, and decline.",
        ],
        "adapt": [
            "The trading ledger is a learning instrument, not a verdict. -0.029R on 1H is information, not judgement.",
            "Rejection from a Dubai role is 'not yet' with a specific gap. Name the gap.",
            "Praise your daughter's effort and persistence, not how clever she is. It starts this early.",
            "The 8/8 APEX stop-outs were a diagnosis of the exit rule, not of your ability.",
        ],
    },

    "Grit": {
        "crux": [
            "Grit = passion + perseverance for long-term goals. It predicts achievement better than talent.",
            "Talent × effort = skill. Skill × effort = achievement. Effort counts twice.",
            "Our preference for 'naturals' hides how much of performance is accumulated work.",
            "Grit is measurable, and it predicts West Point completion, sales retention, and spelling-bee results.",
            "Interest comes before passion. Passion is developed by deliberate cultivation, not found.",
            "Deliberate practice: a stretch goal, full concentration, immediate feedback, repetition on weakness.",
            "Purpose — the belief that the work matters to others — is what sustains effort past year three.",
            "Hope here is not optimism. It is the belief that your own effort changes the outcome.",
            "Goal hierarchy: one top-level goal, mid-level goals as means, low-level as tasks. Drop anything that doesn't serve the top.",
            "Gritty people quit constantly — at the low level. Never at the top.",
            "Grit grows with age and can be trained deliberately.",
            "Hard Thing Rule: everyone does something hard, you may quit only at a natural end point, and you pick the hard thing yourself.",
            "Gritty cultures build gritty individuals. Environment does much of the work.",
        ],
        "learnings": [
            "Consistency over years beats intensity over weeks, and it is less glamorous.",
            "Passion is cultivated, so 'find your passion' is bad advice.",
            "Deliberate practice is uncomfortable by design. Comfortable practice is repetition.",
            "Purpose is what keeps effort going when interest dips.",
        ],
        "examples": [
            "West Point's Beast Barracks: the Grit Scale predicted who stayed better than the Whole Candidate Score.",
            "Spelling-bee finalists were separated by hours of solitary deliberate practice, not by verbal IQ.",
            "Julia Child was 37 and had no cooking credentials when she started. Mastery came from sustained years, not aptitude.",
        ],
        "adapt": [
            "Top-level goal: financial independence with the family in one place. Everything else is a means and can be dropped.",
            "Hard Thing Rule for the household — one hard voluntary thing each, quit only at a season's end.",
            "Deliberate practice on modelling: pick the weakest area, get feedback, repeat. Not more of what already works.",
            "Mid-2026 is 10 months. Grit is what makes month 7 look the same as month 1.",
        ],
    },

    "Outliers": {
        "crux": [
            "Success is not self-made. It is opportunity, timing, culture, and accumulated advantage.",
            "The 10,000-hour rule: elite performance requires enormous accumulated practice — and the chance to get it.",
            "Access to practice hours is unevenly distributed. That access is the hidden variable.",
            "Accumulated advantage: a small early edge compounds into a large late gap.",
            "Relative age effects: Canadian hockey rosters skew to January birthdays because of cut-off dates.",
            "Being born at the right moment matters enormously — 1955 for personal computing, 1830s for US industry.",
            "IQ has a threshold. Past roughly 120, more does not predict more achievement.",
            "Practical intelligence — knowing how to talk to people with power — is taught by families, not schools.",
            "Concerted cultivation versus natural growth: class shapes entitlement to ask.",
            "Cultural legacy persists for generations, in honour cultures and in cockpit hierarchies.",
            "Power Distance Index explains real airline crashes: junior officers who could not contradict captains.",
            "Meaningful work needs autonomy, complexity, and a relationship between effort and reward.",
            "Rice-paddy cultures build a different relationship with persistence than wheat cultures.",
            "We should stop asking what successful people are like and start asking where they came from.",
        ],
        "learnings": [
            "Hours matter, and so does who gets the chance to accumulate them.",
            "Timing is an unearned input that looks like merit afterwards.",
            "Cultural defaults operate below awareness and change outcomes.",
            "Systems can be redesigned to widen access. That is the actionable part.",
        ],
        "examples": [
            "The Beatles played roughly 1,200 live sets in Hamburg before their first success — an unusual volume of practice hours.",
            "Bill Joy had near-unlimited computer time at Michigan in 1971 when almost nobody did.",
            "Korean Air's accident rate fell dramatically after adopting English in the cockpit and flattening hierarchy.",
        ],
        "adapt": [
            "The CA qualification is accumulated hours nobody can shortcut. Treat it as the asset it is.",
            "Timing: AI-assisted finance work in 2026 is the 1955 birthdate. Being early is the advantage.",
            "Practical intelligence is what the Dubai search actually needs — asking, following up, negotiating.",
            "Your daughter's advantage will be an environment where questions get answered. Build that deliberately.",
        ],
    },

    # ── Founders and operators ───────────────────────────────────────────────
    "Shoe Dog": {
        "crux": [
            "Knight started by importing Onitsuka Tigers from a car boot, with no capital and no plan.",
            "Nike ran nearly insolvent for almost two decades while growing fast. Growth consumes cash.",
            "The Crazy Idea only has to be believed by you at the start.",
            "Bank relationships nearly killed the company more often than competitors did.",
            "The Onitsuka betrayal forced Nike into becoming a brand rather than a distributor.",
            "Hire obsessives and misfits. The Buttfaces argued viciously and shipped.",
            "Bowerman's tinkering — waffle iron to waffle sole — was product development without a process.",
            "The $8,000 the US government demanded could have ended it. Legal risk is existential risk.",
            "Don't tell people how to do their jobs. Tell them what to do and let them surprise you.",
            "Losing hurts more than winning feels good, and that asymmetry is fuel and poison.",
            "Cash flow, not profit, decides whether you survive the year.",
            "Faith outlasts evidence for a long time before evidence arrives.",
            "Business is war without bullets — and the price is paid in family time.",
        ],
        "learnings": [
            "Fast growth and near-bankruptcy routinely coexist. Watch cash, not revenue.",
            "Dependence on a single supplier or channel is an existential risk, not an inconvenience.",
            "Obsessive, difficult people build the things that matter.",
            "The cost of building is paid by the people at home too. Count it honestly.",
        ],
        "examples": [
            "Nike hit $8m in sales while unable to make payroll — the classic growth-cash trap.",
            "The waffle sole came from Bowerman pouring rubber into his wife's waffle iron. No R&D budget.",
            "Knight sold shoes out of his car at track meets for years before any retail presence.",
        ],
        "adapt": [
            "Single-channel risk is real: Meta restriction and Railway's shutdown are the same lesson twice.",
            "Cash first. The SIP and 6-month buffer are what let you take a career risk at all.",
            "Ship the imperfect version. Nike's first shoes fell apart and they iterated in public.",
            "Count the family cost of the Dubai push explicitly, and decide it's worth it — don't let it accumulate silently.",
        ],
    },

    "Made in America": {
        "crux": [
            "Walton's obsession was the customer's price, and everything else followed from it.",
            "Buy low, stack it high, sell it cheap. Volume compensates for margin.",
            "Rural small towns were dismissed by competitors. That was the opening.",
            "Control costs better than anyone. Cost advantage forgives many mistakes.",
            "Distribution centres came before the stores they served. Logistics was the real business.",
            "Invest early in information systems. Walmart's data infrastructure preceded everyone's.",
            "Share profits with associates and they behave like owners.",
            "Listen to the people on the floor. They talk to customers; you don't.",
            "Swim upstream. Go the other way when everyone agrees.",
            "Every store must be visited. Management by walking around, constantly.",
            "Copy shamelessly from competitors. Walton toured rivals' stores relentlessly.",
            "Exceed expectations, celebrate success, and keep the culture unembarrassed.",
            "Frugality is cultural, not cosmetic — shared hotel rooms while running a Fortune 500 company.",
        ],
        "learnings": [
            "A cost advantage is a strategy, not an accounting detail.",
            "Infrastructure before expansion, or expansion breaks you.",
            "Frontline staff hold the information leadership needs.",
            "Copying well is faster than inventing badly.",
        ],
        "examples": [
            "Walmart's hub-and-spoke DCs let it saturate regions competitors couldn't serve profitably.",
            "Walton flew his own plane over towns scouting sites, personally, for years.",
            "Profit-sharing from 1971 turned shelf-stackers into shareholders and cut shrinkage.",
        ],
        "adapt": [
            "Your cost advantage is the whole stack running on GitHub Actions and Vercel free tiers. Protect it.",
            "Infrastructure before features: fix the position lifecycle before adding another scanner.",
            "Copy shamelessly — study what the good finance pages do, then do it in your voice.",
            "Swim upstream: everyone posts motivational finance. Post the actual numbers, including the losses.",
        ],
    },

    "The 4-Hour Work Week": {
        "crux": [
            "DEAL: Definition, Elimination, Automation, Liberation.",
            "The New Rich optimise for time and mobility, not for accumulation then retirement.",
            "Deferred-life planning is the default and it is a bad plan.",
            "Dreamlining: cost out the specific life you want. It is usually cheaper than assumed.",
            "Relative income (per hour) beats absolute income.",
            "Pareto: 80% of results come from 20% of inputs. Find and cut the rest.",
            "Parkinson's Law: work expands to fill the time available. Short deadlines force focus.",
            "Use both together — do only the important, and give it very little time.",
            "Selective ignorance: a low-information diet is a productivity intervention.",
            "Batch everything. Email, calls, errands. Context switching is the tax.",
            "Automate with clear rules and delegated authority, or you've just added coordination work.",
            "Build a muse: a product with recurring revenue that doesn't need your presence.",
            "Test demand before building anything. Cheap ads before inventory.",
            "Mini-retirements beat one long retirement at the end.",
            "Fear-setting: define the worst case in detail and it usually shrinks.",
        ],
        "learnings": [
            "Being busy is often a form of avoidance.",
            "Cutting the wrong work beats optimising it.",
            "Deadlines are a focus tool, not just a commitment.",
            "Automation without decision rules just moves the work.",
        ],
        "examples": [
            "Ferriss cut 98% of his client list, kept the top 5, and income rose while hours dropped from 80 to 15.",
            "BrainQUICKEN was validated with small Google Ads spends before stock was ordered.",
            "Fear-setting a trip to London: worst case listed, all reversible. He went.",
        ],
        "adapt": [
            "The bots are the muse infrastructure — they run whether you're interviewing or asleep.",
            "80/20 the content: which posts actually drive followers? Cut the rest.",
            "Batch Telegram and email into two windows. This is the same fix Deep Work prescribes.",
            "Fear-set the Dubai move: worst case is a return to KL with more experience. Reversible.",
        ],
    },
}


def deep_for(book: str) -> dict:
    """Depth block for a book title, or empty dict when none is written yet."""
    return BOOK_DEEP.get(book, {})


def coverage() -> tuple[int, int]:
    """(books with depth, total crux points) — used by the smoke test."""
    return len(BOOK_DEEP), sum(len(v.get("crux", [])) for v in BOOK_DEEP.values())
